export const partners = [{
        'title': 'Молодіжний центр',
        'yourName': 'Мексика',
        'name': 'Сергій Дерека',
        'share': true,
        'img': 'https://i.ibb.co/njf6P2m/dereka.jpg',
        'image': 'https://i.ibb.co/yfzgY67/slide-47.jpg',
        'desc': '',
        'loc': 'с. Максимільянівка Мар"їнської ВЦА  Донецької області',
        'data': '28 грудня 2018 року',
        'text': 'За час роботи став ініціатором та засновником щорічних: обласного <span>"Фестиваля згуртованості молодіжних центрів"</span>, районних військово-патріотичних ігор та спортивних змаганнь <span>"Завжди разом"</span>, виставки народного рукоділля місцевих майстрів <span>"Руками до серця"</span>'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': '380 volt',
        'name': 'Катерина Волкодавець',
        'share': true,
        'img': 'https://i.ibb.co/9s64cxt/volkodavets.jpg',
        'image': 'https://i.ibb.co/k2ybzMC/slide-70.jpg',
        'desc': '',
        'loc': 'м. Курахове Кураховської ВЦА  Донецької області',
        'data': '2019 рік',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2019 та 2021 роках.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Lider-Hub',
        'name': 'Антон Гладкий',
        'share': true,
        'img': 'https://i.ibb.co/WvTzYkT/gladkiy.jpg',
        'image': 'https://i.ibb.co/xghSF9M/slide-101.jpg',
        'desc': '',
        'loc': 'с. Дачне Кураховської ВЦА  Донецької області',
        'data': '2020 році',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2021 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Вікторія',
        'name': 'Олександра Клименко',
        'share': true,
        'img': 'https://i.ibb.co/WBkxr0b/klimenko.jpg',
        'image': 'https://i.ibb.co/wCMjM4M/slide-19.jpg',
        'desc': '',
        'loc': 'м. Мар"їнка Мар"їнської ВЦА  Донецької області',
        'data': '2016 році',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2019 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Надія',
        'name': 'Данил Глущенко',
        'share': true,
        'img': 'https://i.ibb.co/Hx4bq68/gluschenko.jpg',
        'image': 'https://i.ibb.co/2KWjqq6/slide-1.jpg',
        'desc': '',
        'loc': 'м. Красногорівка Мар"їнської ВЦА  Донецької області',
        'data': '2017 році',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2021 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Надія',
        'name': 'Єгор Лагутін',
        'share': false,
        'img': 'https://i.ibb.co/Vpbj0Hr/lagutin.jpg',
        'image': 'https://i.ibb.co/2KWjqq6/slide-1.jpg',
        'desc': '',
        'loc': 'м. Красногорівка Мар"їнської ВЦА  Донецької області',
        'data': '2017 році',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2019 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Крок до мрії',
        'name': 'Катерина Мерзлікіна',
        'share': true,
        'img': 'https://i.ibb.co/WVWX7Tk/merzlikina.jpg',
        'image': 'https://i.ibb.co/BTKXD3V/slide-118.jpg',
        'desc': '',
        'loc': 'с. Новомихайлівка Мар"їнської ВЦА  Донецької області',
        'data': '28 грудня 2018 року',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2019 та 2021 роках.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'ElizavetCity',
        'name': 'Ольга Грищенко',
        'share': true,
        'img': 'https://i.ibb.co/gTp13MM/grischenko.jpg',
        'image': 'https://i.ibb.co/LSPm3bx/slide-121.jpg',
        'desc': '',
        'loc': 'с. Єлізаветівка Мар"їнської ВЦА  Донецької області',
        'data': '2019 році',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2021 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'ElizavetCity',
        'name': 'Дмитро Гришков',
        'share': false,
        'img': 'https://i.ibb.co/K0smCWP/grishko.jpg',
        'image': 'https://i.ibb.co/LSPm3bx/slide-121.jpg',
        'desc': '',
        'loc': 'с. Єлізаветівка Мар"їнської ВЦА  Донецької області',
        'data': '2019 році',
        'text': ''
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Гармонія',
        'name': 'Юлія Кольчик',
        'share': true,
        'img': 'https://i.ibb.co/DwcSNXQ/kolchik.jpg',
        'image': 'https://i.ibb.co/cN4zk0G/slide-20.jpg',
        'desc': '',
        'loc': 'с. Костянтинівка Мар"їнської ВЦА  Донецької області',
        'data': '2019 році',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2021 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Fox',
        'name': 'Марина Ткаченко',
        'share': true,
        'img': 'https://i.ibb.co/mvNgFtb/marina.jpg',
        'image': 'https://i.ibb.co/n0sdYQ6/slide-4.jpg',
        'desc': '',
        'loc': 'с. Катеринівка Мар"їнської ВЦА  Донецької області',
        'data': '2019 році',
        'text': 'Один з активних учасників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> у 2019 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Fox',
        'name': 'Тетяна Василенко',
        'share': false,
        'img': 'https://i.ibb.co/z2ZvmsY/vasilenko.jpg',
        'image': 'https://i.ibb.co/n0sdYQ6/slide-4.jpg',
        'desc': '',
        'loc': 'с. Катеринівка Мар"їнської ВЦА  Донецької області',
        'data': '2019 році',
        'text': ''
    },
    {
        'title': '',
        'yourName': 'ДОДМЦ',
        'name': 'Аліна Сорокіна',
        'share': true,
        'img': 'https://i.ibb.co/Fbx4fGk/sorokima.jpg',
        'image': 'https://i.ibb.co/2k7GCZc/slide-35.jpg',
        'desc': '',
        'loc': 'м. Краматорськ Донецької області',
        'data': '2009 році',
        'text': 'Спонсор обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> у 2021 році.'
    },

]