export const partners = [{
        'title': 'Молодіжний центр',
        'yourName': 'Мексика',
        'name': 'Сергій Дерека',
        'function': 'завідувач',
        'dataName': 'dereka',
        'share': true,
        'img': 'https://i.ibb.co/njf6P2m/dereka.jpg',
        'image': 'https://i.ibb.co/yfzgY67/slide-47.jpg',
        'slideImages': [{
                'text': 'Cемінар <span>"Відкрита молодіжна робота"</span> у 2018 році. Організатори семінару "Асоціація молодіжних центрів України". В межах семінару молодь відвідала міста Дружковка, Сєвєродонецьк, села Максимільянівка та Званівка',
                'img': [
                    'https://i.ibb.co/Bw59sCc/slide-1.webp',
                    'https://i.ibb.co/nCgMtrZ/slide-2.webp',
                    'https://i.ibb.co/D12bfzG/slide-3.webp',
                    'https://i.ibb.co/9NFx8MR/slide-4.webp',
                    'https://i.ibb.co/VLTJ8my/slide-5.webp',
                    'https://i.ibb.co/L89sMLK/slide-6.webp',
                    'https://i.ibb.co/SwXrt64/slide-7.webp',
                    'https://i.ibb.co/Yb2Wcry/slide-8.webp',
                    'https://i.ibb.co/Jm39BMG/slide-9.webp',
                    'https://i.ibb.co/0K84L3w/slide-10.webp',
                    'https://i.ibb.co/Gv9ftJZ/slide-11.webp',
                    'https://i.ibb.co/rpw8RZ3/slide-12.webp',
                    'https://i.ibb.co/hBQXrp2/slide-13.webp',
                    'https://i.ibb.co/JyDkV5z/slide-14.webp',
                    'https://i.ibb.co/CVz0P6h/slide-15.webp',
                    'https://i.ibb.co/1qRfjds/slide-16.webp',
                    'https://i.ibb.co/k1xcvzy/slide-17.webp',
                    'https://i.ibb.co/Nt2PDBt/slide-18.webp',
                    'https://i.ibb.co/0QjFffZ/slide-19.webp',
                    'https://i.ibb.co/vVZ0LwZ/slide-20.webp',
                    'https://i.ibb.co/ZKdm91r/slide-21.webp',
                    'https://i.ibb.co/TYWfsDz/slide-22.webp',
                    'https://i.ibb.co/7XLzZM3/slide-23.webp',
                    'https://i.ibb.co/C2LQmjB/slide-24.webp',
                    'https://i.ibb.co/dt7FYy5/slide-25.webp',
                    'https://i.ibb.co/37ch3T7/slide-26.webp',
                    'https://i.ibb.co/dW06W4T/slide-27.webp',
                    'https://i.ibb.co/MnpwvXd/slide-28.webp',
                    'https://i.ibb.co/nDcmMs5/slide-29.webp',
                    'https://i.ibb.co/D7fV0j3/slide-30.webp',
                    'https://i.ibb.co/1J87tDF/slide-31.webp',
                    'https://i.ibb.co/X770fL3/slide-32.webp',
                    'https://i.ibb.co/TMw8zrg/slide-33.webp',
                    'https://i.ibb.co/q9t2PwZ/slide-34.webp',
                    'https://i.ibb.co/n3qpZjy/slide-35.webp',
                    'https://i.ibb.co/zZ1v1bw/slide-36.webp',
                    'https://i.ibb.co/jfTpXd1/slide-37.webp',
                    'https://i.ibb.co/vjxyT7c/slide-38.webp',
                    'https://i.ibb.co/9c4y85R/slide-39.webp',
                    'https://i.ibb.co/JR8wJN8/slide-40.webp',
                    'https://i.ibb.co/M25892B/slide-41.webp',
                    'https://i.ibb.co/897KSVF/slide-42.webp',
                    'https://i.ibb.co/DkJX1w0/slide-43.webp',
                    'https://i.ibb.co/p171jKJ/slide-44.webp',
                    'https://i.ibb.co/pW8xDcY/slide-45.webp',
                    'https://i.ibb.co/RbfD28C/slide-46.webp',
                    'https://i.ibb.co/tKZgZdj/slide-47.webp',
                    'https://i.ibb.co/nRmNh2f/slide-48.webp',
                    'https://i.ibb.co/TgQKcHM/slide-49.webp',
                    'https://i.ibb.co/6ZrSZg7/slide-50.webp',
                    'https://i.ibb.co/3rGM9hr/slide-51.webp',
                    'https://i.ibb.co/wydG68T/slide-52.webp',
                    'https://i.ibb.co/5nD9M0B/slide-53.webp',
                    'https://i.ibb.co/KhcrDwy/slide-54.webp',
                    'https://i.ibb.co/z4zz6hM/slide-55.webp',
                    'https://i.ibb.co/WGLrpCM/slide-56.webp',
                    'https://i.ibb.co/LkxPMWq/slide-57.webp',
                    'https://i.ibb.co/Jc58PRx/slide-58.webp',
                    'https://i.ibb.co/5YhVxZg/slide-59.webp',
                    'https://i.ibb.co/7j0JqDR/slide-60.webp',
                    'https://i.ibb.co/9NHK9ds/slide-61.webp',
                    'https://i.ibb.co/s93c37g/slide-62.webp',
                    'https://i.ibb.co/RNNVthz/slide-63.webp',
                    'https://i.ibb.co/G5CG074/slide-64.webp',
                    'https://i.ibb.co/mNkTkmv/slide-65.webp',
                    'https://i.ibb.co/3cYkKBN/slide-66.webp',
                    'https://i.ibb.co/72sbCNp/slide-67.webp',
                    'https://i.ibb.co/6YJK58S/slide-68.webp',
                    'https://i.ibb.co/CwL8yrD/slide-69.webp',
                    'https://i.ibb.co/SXvndQy/slide-70.webp',
                    'https://i.ibb.co/X49VzDx/slide-71.webp',
                    'https://i.ibb.co/MVWTG8R/slide-72.webp',
                    'https://i.ibb.co/3s7tXfR/slide-73.webp',
                    'https://i.ibb.co/rHVTxHJ/slide-74.webp',
                    'https://i.ibb.co/9v82g3r/slide-75.webp',
                    'https://i.ibb.co/mNgMSD4/slide-76.webp',
                    'https://i.ibb.co/Ky6QwMR/slide-77.webp',
                    'https://i.ibb.co/M9Q3NWQ/slide-78.webp',
                    'https://i.ibb.co/f8rn2L3/slide-79.webp',
                    'https://i.ibb.co/5YrTg4W/slide-80.webp',
                    'https://i.ibb.co/N2tcS88/slide-81.webp',
                    'https://i.ibb.co/VpmFZ7y/slide-82.webp',
                    'https://i.ibb.co/smywSxX/slide-83.webp',
                    'https://i.ibb.co/1Mwm79z/slide-84.webp',
                    'https://i.ibb.co/V3bcnbZ/slide-85.webp',
                    'https://i.ibb.co/59TP6yF/slide-86.webp',
                    'https://i.ibb.co/TkkXT8t/slide-87.webp',
                    'https://i.ibb.co/Qvh8BB8/slide-88.webp',
                    'https://i.ibb.co/G58czZg/slide-89.webp',
                    'https://i.ibb.co/nbhHYbm/slide-90.webp',
                    'https://i.ibb.co/zmyK2Yd/slide-91.webp',
                    'https://i.ibb.co/YPP5B2k/slide-92.webp',
                    'https://i.ibb.co/YRLyvc7/slide-93.webp',
                    'https://i.ibb.co/WKpGYKW/slide-94.webp',
                    'https://i.ibb.co/NjzbnfH/slide-95.webp',
                    'https://i.ibb.co/vwMy4Mt/slide-96.webp',
                    'https://i.ibb.co/bzSZ9dV/slide-97.webp',
                    'https://i.ibb.co/xXp80C0/slide-98.webp',
                    'https://i.ibb.co/TqZ0pNd/slide-99.webp',
                    'https://i.ibb.co/n6F73st/slide-100.webp',
                    'https://i.ibb.co/RypvsbL/slide-101.webp',
                    'https://i.ibb.co/CWhgRnf/slide-102.webp',
                    'https://i.ibb.co/rkdqPxr/slide-103.webp',
                    'https://i.ibb.co/58DcNcH/slide-104.webp',
                    'https://i.ibb.co/tp4YqsX/slide-105.webp',
                    'https://i.ibb.co/RPNPds7/slide-106.webp',
                    'https://i.ibb.co/cD0tKQr/slide-107.webp',
                    'https://i.ibb.co/zn7Bfp6/slide-108.webp',
                    'https://i.ibb.co/NtSWYRj/slide-109.webp',
                    'https://i.ibb.co/vqQvQhP/slide-110.webp',
                    'https://i.ibb.co/phWdPWY/slide-111.webp',
                    'https://i.ibb.co/fvdmgZM/slide-112.webp',
                    'https://i.ibb.co/6s1jSCm/slide-113.webp',
                    'https://i.ibb.co/JjkF5kV/slide-114.webp',
                    'https://i.ibb.co/1rgsfbK/slide-115.webp',
                    'https://i.ibb.co/Kwjyx9y/slide-116.webp',
                    'https://i.ibb.co/qMTzWZJ/slide-117.webp',
                    'https://i.ibb.co/cFcTNHP/slide-118.webp',
                    'https://i.ibb.co/FHm35Jz/slide-119.webp',
                    'https://i.ibb.co/NnN9GMJ/slide-120.webp',
                    'https://i.ibb.co/B3hRML8/slide-121.webp',
                    'https://i.ibb.co/9bp2220/slide-122.webp',
                    'https://i.ibb.co/zxG5VX1/slide-123.webp',
                    'https://i.ibb.co/180jmqn/slide-124.webp',
                    'https://i.ibb.co/4sZ6B3v/slide-125.webp',
                    'https://i.ibb.co/YPK7jjB/slide-126.webp',
                    'https://i.ibb.co/rfKFxCC/slide-127.webp',
                    'https://i.ibb.co/3RZqkYq/slide-128.webp',
                    'https://i.ibb.co/cYQP4kR/slide-129.webp',
                    'https://i.ibb.co/H49V96p/slide-130.webp',
                    'https://i.ibb.co/D5Zcyyh/slide-131.webp',
                    'https://i.ibb.co/XzLKLD5/slide-132.webp',
                    'https://i.ibb.co/M79gxV0/slide-133.webp',
                    'https://i.ibb.co/TTsCczm/slide-134.webp',
                    'https://i.ibb.co/ZYDBrh2/slide-135.webp',
                    'https://i.ibb.co/gjcqsZB/slide-136.webp',
                    'https://i.ibb.co/sWf29Cy/slide-137.webp',
                    'https://i.ibb.co/q7sfnC8/slide-138.webp'
                ]
            },
            {
                'text': 'Обласний <span>"Фестиваль згуртованості молодіжних центрів"</span>. Один з засновників, організаторів та учасників у 2019 та 2021 роках у с. Максимільянівка',
                'img': [
                    'https://i.ibb.co/cvGYhCy/slide-33.webp',
                    'https://i.ibb.co/jR4sTYg/slide-38.webp',
                    'https://i.ibb.co/T892Yhh/slide-44.webp',
                    'https://i.ibb.co/DRsqYZY/slide-46.webp',
                    'https://i.ibb.co/c20k9cM/slide-24.webp',
                    'https://i.ibb.co/kBJPcyp/slide-23.webp',
                    'https://i.ibb.co/c6Fhny6/slide-53.webp',
                    'https://i.ibb.co/S7yQ7bP/slide-57.webp',
                    'https://i.ibb.co/4grTW7g/slide-58.webp',
                    'https://i.ibb.co/dGbvkqM/slide-60.webp',
                    'https://i.ibb.co/Yfd2y1z/slide-61.webp',
                    'https://i.ibb.co/qsvcQ3G/slide-55.webp',
                    'https://i.ibb.co/cNx37QK/slide-64.webp',
                    'https://i.ibb.co/GWfZtvt/slide-69.webp',
                    'https://i.ibb.co/x6Djh00/slide-79.webp',
                    'https://i.ibb.co/6JmLK6Y/slide-85.webp',
                    'https://i.ibb.co/MkWrtXF/slide-41.webp',
                    'https://i.ibb.co/4jMHWhp/slide-92.webp',
                    'https://i.ibb.co/47gKWRw/slide-96.webp',
                    'https://i.ibb.co/ZXHYFhT/slide-105.webp',
                    'https://i.ibb.co/mXb74fh/slide-108.webp',
                    'https://i.ibb.co/QM4Mpm5/slide-114.webp',
                    'https://i.ibb.co/Jnv7h6X/slide-112.webp',
                    'https://i.ibb.co/82Mm7rS/slide-100.webp',
                    'https://i.ibb.co/PYnprP4/slide-5.webp',
                    'https://i.ibb.co/FxDsjFp/slide-3.webp',
                    'https://i.ibb.co/wK7ksPF/slide-2.webp',
                    'https://i.ibb.co/LvVYk6D/slide-75.webp',
                    'https://i.ibb.co/r0hX9Dx/slide-77.webp'
                ]
            },
            {
                'text': 'Всеукраїнський семінар <span>"Молодіжні центри: стратегія розвитку"</span>. Грудень 2018 р. м. Ірпень',
                'img': [
                    'https://i.ibb.co/NC1CCvS/slide-1.webp',
                    'https://i.ibb.co/qkQZYSy/slide-2.webp',
                    'https://i.ibb.co/qdrxHhd/slide-3.webp',
                    'https://i.ibb.co/Fwqq3gG/slide-4.webp',
                    'https://i.ibb.co/PQQq8qd/slide-5.webp',
                    'https://i.ibb.co/ySwMMbB/slide-6.webp',
                    'https://i.ibb.co/QrNhmdV/slide-7.webp',
                    'https://i.ibb.co/dMtNXNd/slide-8.webp',
                    'https://i.ibb.co/KswChBD/slide-9.webp',
                    'https://i.ibb.co/hc9H6z6/slide-10.webp',
                    'https://i.ibb.co/0c4X5fV/slide-11.webp',
                    'https://i.ibb.co/3FwYwYj/slide-12.webp',
                    'https://i.ibb.co/KG89WWt/slide-13.webp'
                ]
            },
            {
                'text': 'Учасник обласного семінару<span>"Національна молодіжна рада України"</span>.  2018 р. М. Святогарськ',
                'img': [
                    'https://i.ibb.co/6XxGSBh/slide-1.webp',
                    'https://i.ibb.co/F0hPFKm/slide-2.webp',
                    'https://i.ibb.co/hMJxmCY/slide-3.webp',
                    'https://i.ibb.co/kh8Hv6X/slide-4.webp',
                    'https://i.ibb.co/0YKdh9m/slide-5.webp',
                    'https://i.ibb.co/P6wKx6N/slide-6.webp',
                    'https://i.ibb.co/9q6NMYH/slide-7.webp',
                    'https://i.ibb.co/rkhbKBr/slide-8.webp',
                    'https://i.ibb.co/mqDJTTc/slide-9.webp',
                    'https://i.ibb.co/HTPF1b0/slide-10.webp',
                    'https://i.ibb.co/xhfFtnj/slide-11.webp',
                    'https://i.ibb.co/q5StSz7/slide-12.webp',
                    'https://i.ibb.co/mNGY869/slide-13.webp',
                    'https://i.ibb.co/CQWTWM2/slide-14.webp',
                    'https://i.ibb.co/KhKYyjp/slide-15.webp',
                    'https://i.ibb.co/b6mX70p/slide-16.webp',
                    'https://i.ibb.co/xGVXrDX/slide-17.webp',
                    'https://i.ibb.co/ww2SjLX/slide-18.webp',
                    'https://i.ibb.co/tctST3g/slide-19.webp',
                    'https://i.ibb.co/Dg5LDV8/slide-20.webp',
                    'https://i.ibb.co/PxbC7J9/slide-21.webp',
                    'https://i.ibb.co/YWYmhfj/slide-22.webp',
                    'https://i.ibb.co/ZzM3Sxx/slide-23.webp',
                    'https://i.ibb.co/2Sptphm/slide-24.webp',
                    'https://i.ibb.co/hssHbh6/slide-25.webp',
                    'https://i.ibb.co/P4w2y8R/slide-26.webp',
                    'https://i.ibb.co/HPDY1J1/slide-27.webp',
                    'https://i.ibb.co/HHM12DT/slide-28.webp',
                    'https://i.ibb.co/WWJ1M7Z/slide-29.webp'
                ]
            },
            {
                'text': 'Учасник тренінгу з командоутворення 2019 - 2020 роки м. Буча.',
                'img': [
                    'https://i.ibb.co/YyC2qVk/slide-1.webp',
                    'https://i.ibb.co/RjMZzc7/slide-2.webp',
                    'https://i.ibb.co/5Y6SxSL/slide-3.webp',
                    'https://i.ibb.co/HgXRx5G/slide-4.webp',
                    'https://i.ibb.co/sH3txBF/slide-5.webp',
                    'https://i.ibb.co/s9g6ptj/slide-6.webp',
                    'https://i.ibb.co/ZVCLXCx/slide-7.webp',
                    'https://i.ibb.co/yhphZbj/slide-8.webp',
                    'https://i.ibb.co/PMfHnnf/slide-9.webp',
                    'https://i.ibb.co/CmzZt6r/slide-10.webp',
                    'https://i.ibb.co/BqjK9zc/slide-11.webp',
                    'https://i.ibb.co/T26rskb/slide-12.webp',
                    'https://i.ibb.co/cwv6rB5/slide-13.webp',
                    'https://i.ibb.co/MN3TLGm/slide-14.webp',
                    'https://i.ibb.co/StTcLv5/slide-15.webp',
                    'https://i.ibb.co/VCFcSDK/slide-16.webp',
                    'https://i.ibb.co/YtK1QXX/slide-17.webp',
                    'https://i.ibb.co/3BV9Cxj/slide-18.webp'
                ]
            },
            {
                'text': 'Учасник обласного семінара <span>"ПроМц"</span> у 2019 - 2021 роках м. Святогірськ',
                'img': [
                    'https://i.ibb.co/JtzhnS2/slide-5.jpg',
                    'https://i.ibb.co/n6SQHnC/slide-1.jpg',
                    'https://i.ibb.co/Qf45kjx/slide-3.jpg',
                    'https://i.ibb.co/X37scPC/slide-11.jpg',
                    'https://i.ibb.co/StKcFxk/slide-13.jpg',
                    'https://i.ibb.co/X7f1HsT/slide-17.jpg',
                    'https://i.ibb.co/rc2vZzz/slide-21.jpg',
                    'https://i.ibb.co/72HMzvZ/slide-23.jpg',
                    'https://i.ibb.co/MsydhGm/slide-36.jpg',
                    'https://i.ibb.co/XDnBVC3/slide-41.jpg',
                    'https://i.ibb.co/ByXwgBn/slide-42.jpg',
                    'https://i.ibb.co/YX8PGMW/slide-45.jpg',
                    'https://i.ibb.co/SsbdG58/slide-46.jpg',
                    'https://i.ibb.co/Fwm5XKB/slide-47.jpg',
                    'https://i.ibb.co/18jgFMX/slide-48.jpg',
                    'https://i.ibb.co/vJ11B3K/18.jpg',
                    'https://i.ibb.co/MpqmLHt/16.jpg',
                    'https://i.ibb.co/vw3kjBP/12.jpg',
                    'https://i.ibb.co/tQgH0Rk/7.jpg',
                    'https://i.ibb.co/5jTNsJv/5.jpg',
                    'https://i.ibb.co/w78rN8y/1.jpg',
                    'https://i.ibb.co/541V38D/17.jpg',
                    'https://i.ibb.co/YWkQfLx/1.jpg',
                    ''
                ]
            },
            {
                'text': 'Учасник тренінгу <span>"Молодіжний працівник"</span> 2019 р. м. Краматорськ',
                'img': [
                    'https://i.ibb.co/Jt3h7m8/22.jpg',
                    'https://i.ibb.co/zJ7T454/16.jpg',
                    'https://i.ibb.co/RQ5Lmm8/26.jpg',
                    'https://i.ibb.co/pJD6tkd/25.jpg',
                    'https://i.ibb.co/yP3LX8w/24.jpg',
                    'https://i.ibb.co/HTnjBLY/15.jpg',
                    'https://i.ibb.co/7tk6XfL/13.jpg',
                    'https://i.ibb.co/85QqKWX/10.jpg',
                    'https://i.ibb.co/pyp38Xm/3.jpg'
                ]
            },
            {
                'text': 'Учасник обласного семінару <span>"Молодіжні хаби - ключ до розвитку громад"</span> у 2019 році м. Святогірськ',
                'img': [
                    'https://i.ibb.co/c6mBxp8/slide-3.jpg',
                    'https://i.ibb.co/swT3xbm/slide-1.jpg',
                    'https://i.ibb.co/26Cm6h8/slide-5.jpg',
                    'https://i.ibb.co/bX6JyYS/slide-6.jpg',
                    'https://i.ibb.co/LPJ1MKx/slide-7.jpg',
                    'https://i.ibb.co/9bzbbry/slide-8.jpg',
                    'https://i.ibb.co/6PgW8Yx/slide-9.jpg',
                    'https://i.ibb.co/YTx6HyD/slide-10.jpg',
                    'https://i.ibb.co/cQXwk0C/slide-11.jpg',
                    'https://i.ibb.co/gPxNxZr/slide-12.jpg',
                    'https://i.ibb.co/0hMypJL/slide-13.jpg',
                    'https://i.ibb.co/WHGn9Dx/slide-14.jpg',
                    'https://i.ibb.co/hRkKdn3/slide-15.jpg',
                    'https://i.ibb.co/4Z3g9rQ/slide-16.jpg',
                    'https://i.ibb.co/3YY0YVV/slide-17.jpg',
                    'https://i.ibb.co/mqjdbmr/slide-19.jpg',
                    'https://i.ibb.co/wKQ5GpB/slide-20.jpg',
                    'https://i.ibb.co/5sW56Bs/slide-21.jpg',
                    'https://i.ibb.co/z8tZ2Mj/slide-22.jpg',
                    'https://i.ibb.co/XYyM270/slide-24.jpg',
                    'https://i.ibb.co/JFsByhv/slide-25.jpg',
                    'https://i.ibb.co/850Httb/slide-26.jpg',
                    'https://i.ibb.co/gdJkkmw/slide-27.jpg',
                    'https://i.ibb.co/6bTk7Cj/slide-28.jpg',
                    'https://i.ibb.co/R2Krh0q/slide-29.jpg',
                    'https://i.ibb.co/18SQ8Tb/slide-30.jpg',
                    'https://i.ibb.co/3NMG7SG/slide-31.jpg',
                    'https://i.ibb.co/HGF0xkk/slide-32.jpg',
                    'https://i.ibb.co/0C2SjCC/slide-33.jpg',
                    'https://i.ibb.co/720fDnQ/slide-34.jpg',
                    'https://i.ibb.co/B3BBXvt/slide-36.jpg',
                    'https://i.ibb.co/Q8spPm7/slide-37.jpg',
                    'https://i.ibb.co/Fn5NnsS/slide-38.jpg',
                    'https://i.ibb.co/Hth88WX/slide-39.jpg',
                    'https://i.ibb.co/nzPyZfK/slide-40.jpg',
                    'https://i.ibb.co/NCDjT7Z/slide-41.jpg',
                    'https://i.ibb.co/BLRrmv6/slide-42.jpg',
                    'https://i.ibb.co/55Nzq1B/slide-43.jpg',
                    'https://i.ibb.co/3SxtL1Y/slide-44.jpg',
                    'https://i.ibb.co/d0YWBfr/slide-45.jpg',
                    'https://i.ibb.co/YhTywV4/slide-47.jpg',
                    'https://i.ibb.co/sK1r5TX/slide-48.jpg',
                    'https://i.ibb.co/H4dgqGj/slide-51.jpg',
                    'https://i.ibb.co/51BXHYv/slide-50.jpg',
                    'https://i.ibb.co/6gtSmnK/slide-52.jpg',
                    'https://i.ibb.co/mDCysYf/slide-53.jpg',
                    'https://i.ibb.co/NtPB0bC/slide-54.jpg',
                    'https://i.ibb.co/wWvkFtn/slide-55.jpg',
                    'https://i.ibb.co/gywnGmw/slide-57.jpg',
                    'https://i.ibb.co/1XYmGJr/slide-58.jpg',
                    'https://i.ibb.co/y8FP47d/slide-59.jpg',
                    'https://i.ibb.co/M2mHm1T/slide-60.jpg',
                    'https://i.ibb.co/xqMFwkQ/slide-61.jpg',
                    'https://i.ibb.co/LnNs1zL/slide-62.jpg',
                    'https://i.ibb.co/SN71fCQ/slide-63.jpg'
                ]
            },
            {
                'text': 'Учасник спеціалізованого тренінгу з ЗОЖ <span>"Молодіжний працівник"</span> 2020 р. м. Харків',
                'img': [
                    'https://i.ibb.co/x3q1H29/7.jpg',
                    'https://i.ibb.co/PCJ5cXr/2.jpg',
                    'https://i.ibb.co/wzHPXjy/3.jpg',
                    'https://i.ibb.co/kqfgdmh/5.jpg',
                    'https://i.ibb.co/X2VGcbL/8.jpg',
                    'https://i.ibb.co/SdzvK7G/11.jpg',
                    'https://i.ibb.co/jVvjkcJ/12.jpg',
                    'https://i.ibb.co/GCjdqmN/14.jpg',
                    'https://i.ibb.co/BgJN7ZV/15.jpg',
                    'https://i.ibb.co/m6zbPn4/22.jpg'
                ]
            },
            {
                'text': 'Учасник тренінгу <span>"Залучення ресурсів для організацій громадянського суспільства"</span> м. Святогірськ 2019 рік. Тренерка Соломія Боршош.',
                'img': [
                    'https://i.ibb.co/mhvMrj1/1.jpg',
                    'https://i.ibb.co/1Gsh5JP/2.jpg',
                    'https://i.ibb.co/JKYPMFZ/3.jpg',
                    'https://i.ibb.co/8Dy1Jv2/4.jpg',
                    'https://i.ibb.co/WfdNB7b/5.jpg',
                    'https://i.ibb.co/hKfCJMf/6.jpg',
                    'https://i.ibb.co/0FNDgWS/7.jpg',
                    'https://i.ibb.co/v4ChFp2/8.jpg'
                ]
            },
            {
                'text': 'Учасник тренінгу <span>"«Маршрут Безбеки» та «Профілактика ВІЛ/СНІДу на робочому місці»"</span> м. Маріуполь 2019 рік. Тренерка Ірина Мінакова.',
                'img': [
                    'https://i.ibb.co/j5VwWWg/11.jpg',
                    'https://i.ibb.co/xDJG4G7/1.jpg',
                    'https://i.ibb.co/z5hGz1y/2.jpg',
                    'https://i.ibb.co/qDSjBfk/3.jpg',
                    'https://i.ibb.co/r4M5bxw/4.jpg',
                    'https://i.ibb.co/K5Gdkn8/10.jpg',
                    'https://i.ibb.co/C9G23Jd/5.jpg',
                    'https://i.ibb.co/HtWHWdd/6.jpg',
                    'https://i.ibb.co/8KQ6vxh/7.jpg',
                    'https://i.ibb.co/Jv3V9m8/8.jpg',
                    'https://i.ibb.co/cbmPwHq/9.jpg',
                    'https://i.ibb.co/HGn72my/12.jpg',
                    'https://i.ibb.co/tJGMJ54/13.jpg',
                    'https://i.ibb.co/tPpRGH4/14.jpg',
                    'https://i.ibb.co/0Zn50yR/15.jpg',
                    'https://i.ibb.co/4V4rN0n/16.jpg',
                    'https://i.ibb.co/Mg5kpw9/17.jpg',
                    'https://i.ibb.co/vjz52Y7/18.jpg'
                ]
            },
            {
                'text': 'Учасник третього всеукраїнського форуму молодіжних працівників та працівниць <span>"Digital у молодіжній роботі"</span> 31.11 - 2.12 2019 року м. Луцьк',
                'img': [
                    'https://i.ibb.co/rHNtvFv/1.jpg',
                    'https://i.ibb.co/BrHRgcp/2.jpg',
                    'https://i.ibb.co/68sSsBX/3.jpg',
                    'https://i.ibb.co/DLdMTNP/4.jpg',
                    'https://i.ibb.co/RcSkCPz/5.jpg',
                    'https://i.ibb.co/kG28BzT/6.jpg',
                    'https://i.ibb.co/pWdtJMx/7.jpg',
                    'https://i.ibb.co/Bj9FQQh/8.jpg',
                    'https://i.ibb.co/vZvWY6V/9.jpg',
                    'https://i.ibb.co/2KN3QWR/10.jpg',
                    'https://i.ibb.co/L532nrb/11.jpg',
                    'https://i.ibb.co/gP76jv9/12.jpg',
                    'https://i.ibb.co/MNBfb0c/13.jpg',
                    'https://i.ibb.co/59pnyg6/14.jpg',
                    'https://i.ibb.co/jJHz35W/15.jpg',
                    'https://i.ibb.co/8sqNVpW/16.jpg',
                    'https://i.ibb.co/kxw2wV5/17.jpg',
                    'https://i.ibb.co/cC4WWNw/18.jpg',
                    'https://i.ibb.co/19TFPKy/19.jpg',
                    'https://i.ibb.co/hBC5549/20.jpg',
                    'https://i.ibb.co/BrPfmd6/21.jpg',
                    'https://i.ibb.co/vv7vJ4Q/22.jpg',
                    'https://i.ibb.co/m0bK6R2/23.jpg',
                    'https://i.ibb.co/LdqF35X/24.jpg',
                    'https://i.ibb.co/rdZbS1N/25.jpg',
                    'https://i.ibb.co/PT6CqM8/26.jpg',
                    'https://i.ibb.co/Jrn4Zqx/27.jpg',
                    'https://i.ibb.co/D9XKRbp/28.jpg',
                    'https://i.ibb.co/PwZm7bz/29.jpg',
                    'https://i.ibb.co/ZBnByfK/30.jpg',
                    'https://i.ibb.co/Czc8Gsc/31.jpg',
                    'https://i.ibb.co/PrBxVtS/32.jpg',
                    'https://i.ibb.co/3Ms0C1R/33.jpg'
                ]
            },
            {
                'text': 'Учасник та фіналіст тренінгу молодіжних працівників та їх команд <span>"Мережа змін"</span>',
                'img': [
                    'https://i.ibb.co/9bKn8Mk/slide-169.jpg',
                    'https://i.ibb.co/gPggpps/slide-161.jpg',
                    'https://i.ibb.co/9HRVFx9/slide-178.jpg',
                    'https://i.ibb.co/D7yfq0P/slide-175.jpg',
                    'https://i.ibb.co/7p7ztdR/slide-174.jpg',
                    'https://i.ibb.co/CBybT7x/slide-173.jpg',
                    'https://i.ibb.co/fY3C10m/slide-171.jpg',
                    'https://i.ibb.co/V3jgTvn/slide-170.jpg',
                    'https://i.ibb.co/ph466yT/slide-168.jpg',
                    'https://i.ibb.co/r4D0BzT/slide-167.jpg',
                    'https://i.ibb.co/GJ2F5D6/slide-166.jpg',
                    'https://i.ibb.co/r4c8z2g/slide-164.jpg',
                    'https://i.ibb.co/JF0tzTz/slide-163.jpg',
                    'https://i.ibb.co/Lk0cGRk/slide-162.jpg',
                    'https://i.ibb.co/Z8xQ62N/slide-160.jpg',
                    'https://i.ibb.co/kJLJtnN/slide-159.jpg',
                    'https://i.ibb.co/SPVdLtH/slide-158.jpg',
                    'https://i.ibb.co/DVXQKVn/slide-157.jpg',
                    'https://i.ibb.co/yYzFw1m/slide-156.jpg',
                    'https://i.ibb.co/xMnqgH4/slide-155.jpg',
                    'https://i.ibb.co/HhVtPN1/slide-152.jpg',
                    'https://i.ibb.co/BVmLjYh/slide-150.jpg',
                    'https://i.ibb.co/Hz2pMV7/slide-144.jpg',
                    'https://i.ibb.co/rvPKZ8J/slide-141.jpg',
                    'https://i.ibb.co/pZXS8z7/slide-137.jpg',
                    'https://i.ibb.co/5nWGPVP/slide-129.jpg',
                    'https://i.ibb.co/YP5kkN6/slide-128.jpg',
                    'https://i.ibb.co/VjftjcJ/slide-125.jpg',
                    'https://i.ibb.co/SNYNrCF/slide-122.jpg',
                    'https://i.ibb.co/DMmJ6JT/slide-116.jpg',
                    'https://i.ibb.co/QPpsLJ2/slide-111.jpg',
                    'https://i.ibb.co/GpBns7M/slide-110.jpg',
                    'https://i.ibb.co/zf1MXS8/slide-109.jpg',
                    'https://i.ibb.co/ZB2YKGm/slide-108.jpg',
                    'https://i.ibb.co/0qmq52V/slide-107.jpg',
                    'https://i.ibb.co/4TbRsWf/slide-104.jpg',
                    'https://i.ibb.co/mHmjsb1/slide-102.jpg',
                    'https://i.ibb.co/jfNYTMn/slide-101.jpg',
                    'https://i.ibb.co/cQYgHtn/slide-96.jpg',
                    'https://i.ibb.co/pwW43Cs/slide-95.jpg',
                    'https://i.ibb.co/TcqcqXJ/slide-92.jpg',
                    'https://i.ibb.co/CsPhXTn/slide-91.jpg',
                    'https://i.ibb.co/JsfzCc5/slide-88.jpg',
                    'https://i.ibb.co/8Y7Jwgh/slide-87.jpg',
                    'https://i.ibb.co/Z2sbLWD/slide-80.jpg',
                    'https://i.ibb.co/DRWBJgz/slide-73.jpg',
                    'https://i.ibb.co/2dd0m7R/slide-65.jpg',
                    'https://i.ibb.co/b7DqzHB/slide-62.jpg',
                    'https://i.ibb.co/BrQmY1g/slide-60.jpg',
                    'https://i.ibb.co/4WVsxDW/slide-52.jpg',
                    'https://i.ibb.co/wR0w8Kv/slide-46.jpg',
                    'https://i.ibb.co/PTd9jts/slide-44.jpg',
                    'https://i.ibb.co/KDMwnnd/slide-40.jpg',
                    'https://i.ibb.co/bWZRBTx/slide-39.jpg',
                    'https://i.ibb.co/mzQRQ73/slide-37.jpg',
                    'https://i.ibb.co/rpzhPBS/slide-16.jpg',
                    'https://i.ibb.co/cySvb2d/slide-2.jpg',
                    'https://i.ibb.co/wpJb2Bq/slide-8.jpg',
                    'https://i.ibb.co/SrxSbrJ/slide-7.jpg',
                    'https://i.ibb.co/dr8q3Sr/slide-6.jpg',
                    'https://i.ibb.co/7VRR37m/slide-5.jpg',
                    'https://i.ibb.co/2qYnrCD/slide-4.jpg',
                    'https://i.ibb.co/SvLs3fT/slide-3.jpg',
                    'https://i.ibb.co/sHcBFsm/slide-1.jpg',
                    'https://i.ibb.co/W5D7gst/slide-2.jpg',
                    'https://i.ibb.co/4YXRRV8/slide-3.jpg',
                    'https://i.ibb.co/T45R7Qn/slide-4.jpg',
                    'https://i.ibb.co/BgvVFrJ/slide-5.jpg',
                    'https://i.ibb.co/Qd42TX0/slide-6.jpg',
                    'https://i.ibb.co/8YxS08w/slide-7.jpg',
                    'https://i.ibb.co/tzFnJY9/slide-8.jpg',
                    'https://i.ibb.co/fqCywhh/slide-9.jpg',
                    'https://i.ibb.co/fXYVRWs/slide-10.jpg',
                    'https://i.ibb.co/VmzK5Fq/slide-11.jpg',
                    'https://i.ibb.co/YyGYYhP/slide-12.jpg',
                    'https://i.ibb.co/XZLRB6n/slide-13.jpg',
                    'https://i.ibb.co/xLMhJW3/slide-14.jpg',
                    'https://i.ibb.co/pQDwQzN/slide-15.jpg',
                    'https://i.ibb.co/JdhbhFd/slide-16.jpg',
                    'https://i.ibb.co/RYGQkWH/slide-17.jpg',
                    'https://i.ibb.co/PtF6MhX/slide-18.jpg',
                    'https://i.ibb.co/hDfKR3X/slide-19.jpg',
                    'https://i.ibb.co/qjDtNpc/slide-20.jpg',
                    'https://i.ibb.co/K6gC6BL/slide-21.jpg',
                    'https://i.ibb.co/kghL4X2/slide-22.jpg',
                    'https://i.ibb.co/rFbn9k8/slide-23.jpg',
                    'https://i.ibb.co/d0rxGkp/slide-24.jpg',
                    'https://i.ibb.co/x2fq9nP/slide-25.jpg'
                ]
            },
            {
                'text': 'Засновник щорічних військово-патріотичних ігор та спортивних змаганнь <span>"Завжди разом"</span> за підтримки цивільно-військового співробітництва с. Максимільянівка з 2019 року',
                'img': [
                    'https://i.ibb.co/p11SchS/slide-1.jpg',
                    'https://i.ibb.co/6bq5N2H/slide-2.jpg',
                    'https://i.ibb.co/1ZDdYFC/slide-3.jpg',
                    'https://i.ibb.co/s6dymcD/slide-4.jpg',
                    'https://i.ibb.co/bmv1s9h/slide-5.jpg',
                    'https://i.ibb.co/X8Bwrfq/slide-6.jpg',
                    'https://i.ibb.co/yQYpSr1/slide-7.jpg',
                    'https://i.ibb.co/qBxkW7c/slide-8.jpg',
                    'https://i.ibb.co/p1YCQgj/slide-9.jpg',
                    'https://i.ibb.co/Z6hvTcD/slide-10.jpg',
                    'https://i.ibb.co/fvGq4YG/slide-11.jpg',
                    'https://i.ibb.co/q0JdR2k/slide-12.jpg',
                    'https://i.ibb.co/YDcgvNw/slide-13.jpg',
                    'https://i.ibb.co/3Bb1P2Q/slide-14.jpg',
                    'https://i.ibb.co/K9f089r/slide-15.jpg',
                    'https://i.ibb.co/2vHXpjM/slide-16.jpg',
                    'https://i.ibb.co/wr2HhgT/slide-17.jpg',
                    'https://i.ibb.co/yR1JPZ7/slide-18.jpg',
                    'https://i.ibb.co/3s1CS0F/slide-19.jpg',
                    'https://i.ibb.co/23S8YHr/slide-20.jpg',
                    'https://i.ibb.co/LtZkSRR/slide-21.jpg',
                    'https://i.ibb.co/869LmDb/slide-22.jpg',
                    'https://i.ibb.co/rFKBV8H/slide-23.jpg',
                    'https://i.ibb.co/tZWbGZ5/slide-24.jpg',
                    'https://i.ibb.co/DYdmG42/slide-25.jpg',
                    'https://i.ibb.co/Y8wYKkN/slide-26.jpg',
                    'https://i.ibb.co/1m0fjpv/slide-27.jpg',
                    'https://i.ibb.co/H7KpGwx/slide-28.jpg',
                    'https://i.ibb.co/q5Yb7Fg/slide-29.jpg',
                    'https://i.ibb.co/2FtKVLP/slide-30.jpg',
                    'https://i.ibb.co/LNk5X5M/slide-31.jpg',
                    'https://i.ibb.co/vjsJv2X/slide-32.jpg',
                    'https://i.ibb.co/LtZKG4L/slide-33.jpg',
                    'https://i.ibb.co/DMgLgyW/slide-34.jpg',
                    'https://i.ibb.co/7jYPKyc/slide-35.jpg',
                    'https://i.ibb.co/ZccVXPS/slide-36.jpg',
                    'https://i.ibb.co/yX48VJm/slide-37.jpg',
                    'https://i.ibb.co/f877dNJ/slide-38.jpg',
                    'https://i.ibb.co/dDgy2mZ/slide-39.jpg',
                    'https://i.ibb.co/RP1fvhJ/slide-40.jpg',
                    'https://i.ibb.co/jMyBRP5/slide-41.jpg',
                    'https://i.ibb.co/17KJJp9/slide-42.jpg',
                    'https://i.ibb.co/YRCL3rN/slide-43.jpg',
                    'https://i.ibb.co/zNFPMD9/slide-44.jpg',
                    'https://i.ibb.co/k3dJnp2/slide-45.jpg',
                    'https://i.ibb.co/j8gMfL8/slide-47.jpg',
                    'https://i.ibb.co/kQ6Lk1d/slide-48.jpg',
                    'https://i.ibb.co/X4fnvvJ/slide-49.jpg'
                ]
            },
            {
                'text': 'Засновник щомісячних прямих ефірів на Youtube каналі',
                'img': [
                    'https://i.ibb.co/sbDgw5q/slide-1.jpg',
                    'https://i.ibb.co/B6psxm7/slide-2.jpg',
                    'https://i.ibb.co/0rvj3pr/slide-3.jpg',
                    'https://i.ibb.co/sqYVSs9/slide-4.jpg',
                    'https://i.ibb.co/Jqkbn3d/slide-5.jpg',
                    'https://i.ibb.co/mGLKzXs/slide-6.jpg',
                    'https://i.ibb.co/sHGzqMb/slide-7.jpg'
                ]
            }
        ],
        'desc': '',
        'loc': 'с. Максимільянівка Мар"їнської ВЦА  Донецької області',
        'data': '28 грудня 2018 року',
        'text': 'За час роботи став ініціатором та засновником щорічних: обласного <span>"Фестиваля згуртованості молодіжних центрів"</span>, районних військово-патріотичних ігор та спортивних змаганнь <span>"Завжди разом"</span>, виставки народного рукоділля місцевих майстрів <span>"Руками до серця"</span>'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': '380 volt',
        'name': 'Катерина Волкодавець',
        'function': 'завідувач',
        'dataName': 'volkodavets',
        'share': true,
        'img': 'https://i.ibb.co/9s64cxt/volkodavets.jpg',
        'image': 'https://i.ibb.co/k2ybzMC/slide-70.jpg',
        'slideImages': [{
                'text': 'Cемінар <span>"Відкрита молодіжна робота"</span> у 2018 році. Організатори семінару "Асоціація молодіжних центрів України". В межах семінару молодь відвідала міста Дружковка, Сєвєродонецьк, села Максимільянівка та Званівка',
                'img': [
                    'https://i.ibb.co/YXzvfNX/1.jpg',
                    'https://i.ibb.co/8PjJrgp/2.jpg',
                    'https://i.ibb.co/5YnfDpD/3.jpg',
                    'https://i.ibb.co/8b1NQ72/4.jpg',
                    'https://i.ibb.co/DkJCjD1/5.jpg',
                    'https://i.ibb.co/W6B6ZZC/6.jpg',
                    'https://i.ibb.co/35bkDvw/7.jpg',
                    'https://i.ibb.co/VVnKxRJ/8.jpg',
                    'https://i.ibb.co/HhQQBtR/9.jpg',
                    'https://i.ibb.co/64L0kqF/10.jpg',
                    'https://i.ibb.co/c8B7cpr/11.jpg',
                    'https://i.ibb.co/w6Nnpz6/12.jpg',
                    'https://i.ibb.co/JxnZ8yt/13.jpg',
                    'https://i.ibb.co/Z6qrnj8/10.jpg'
                ]
            },
            {
                'text': 'Обласний <span>"Фестиваль згуртованості молодіжних центрів"</span>. Одна з засновників, організаторів та учасників у 2019 та 2021 роках у с. Максимільянівка',
                'img': [
                    'https://i.ibb.co/gFhq472/1.jpg',
                    'https://i.ibb.co/gwtPY5N/2.jpg',
                    'https://i.ibb.co/F0dCrw1/3.jpg',
                    'https://i.ibb.co/J3HFrF8/4.jpg',
                    'https://i.ibb.co/KFK91Kx/5.jpg',
                    'https://i.ibb.co/X4kB564/6.jpg',
                    'https://i.ibb.co/ZX95h1d/7.jpg',
                    'https://i.ibb.co/4MjgWNW/8.jpg',
                    'https://i.ibb.co/vzWTSyF/9.jpg',
                    'https://i.ibb.co/NF1nSyp/10.jpg',
                    'https://i.ibb.co/mGtnyNc/slide-100.jpg'
                ]
            },
            {
                'text': 'Учасник обласного семінару <span>"Молодіжні хаби - ключ до розвитку громад"</span> у 2019 році м. Святогірськ',
                'img': [
                    'https://i.ibb.co/HgKCN76/slide-2.jpg',
                    'https://i.ibb.co/gdJkkmw/slide-27.jpg',
                    'https://i.ibb.co/850Httb/slide-26.jpg',
                    'https://i.ibb.co/jGzSR9P/slide-23.jpg',
                    'https://i.ibb.co/5sW56Bs/slide-21.jpg',
                    'https://i.ibb.co/mqjdbmr/slide-19.jpg',
                    'https://i.ibb.co/gPxNxZr/slide-12.jpg',
                    'https://i.ibb.co/cQXwk0C/slide-11.jpg',
                    'https://i.ibb.co/bX6JyYS/slide-6.jpg',
                    'https://i.ibb.co/c6mBxp8/slide-3.jpg',
                    'https://i.ibb.co/LnNs1zL/slide-62.jpg',
                    'https://i.ibb.co/M2mHm1T/slide-60.jpg',
                    'https://i.ibb.co/y8FP47d/slide-59.jpg',
                    'https://i.ibb.co/gywnGmw/slide-57.jpg',
                    'https://i.ibb.co/6gtSmnK/slide-52.jpg',
                    'https://i.ibb.co/51BXHYv/slide-50.jpg',
                    'https://i.ibb.co/H4dgqGj/slide-51.jpg',
                    'https://i.ibb.co/zZf02wx/slide-49.jpg',
                    'https://i.ibb.co/Bqkd3tC/slide-46.jpg',
                    'https://i.ibb.co/3SxtL1Y/slide-44.jpg',
                    'https://i.ibb.co/Pjf3D8Y/slide-35.jpg'
                ]
            },
            {
                'text': 'Учасник тренінгу <span>"Залучення ресурсів для організацій громадянського суспільства"</span> м. Святогірськ 2019 рік. Тренерка Соломія Боршош.',
                'img': [
                    'https://i.ibb.co/mhvMrj1/1.jpg',
                    'https://i.ibb.co/JKYPMFZ/3.jpg',
                    'https://i.ibb.co/8Dy1Jv2/4.jpg',
                    'https://i.ibb.co/WfdNB7b/5.jpg',
                    'https://i.ibb.co/hKfCJMf/6.jpg',
                    'https://i.ibb.co/0FNDgWS/7.jpg'
                ]
            },
            {
                'text': 'Учасник тренінгу <span>"Молодіжний працівник"</span> 2019 р. м. Краматорськ',
                'img': [
                    'https://i.ibb.co/Jt3h7m8/22.jpg',
                    'https://i.ibb.co/RQ5Lmm8/26.jpg',
                    'https://i.ibb.co/7tk6XfL/13.jpg',
                    'https://i.ibb.co/85QqKWX/10.jpg',
                    'https://i.ibb.co/4TVxRmg/20.jpg',
                    'https://i.ibb.co/3smf7RW/28.jpg',
                    'https://i.ibb.co/FhCDP3Y/27.jpg',
                    'https://i.ibb.co/1QL0sJ0/12.jpg',
                    'https://i.ibb.co/2jXT7R0/11.jpg',
                    'https://i.ibb.co/51bLKtv/14.jpg',

                ]
            },
            {
                'text': 'Учасник тренінгу з командоутворення 2019 - 2020 роки м. Буча.',
                'img': [
                    'https://i.ibb.co/YyC2qVk/slide-1.webp',
                    'https://i.ibb.co/RjMZzc7/slide-2.webp',
                    'https://i.ibb.co/5Y6SxSL/slide-3.webp',
                    'https://i.ibb.co/HgXRx5G/slide-4.webp',
                    'https://i.ibb.co/sH3txBF/slide-5.webp',
                    'https://i.ibb.co/s9g6ptj/slide-6.webp',
                    'https://i.ibb.co/ZVCLXCx/slide-7.webp',
                    'https://i.ibb.co/yhphZbj/slide-8.webp',
                    'https://i.ibb.co/PMfHnnf/slide-9.webp',
                    'https://i.ibb.co/CmzZt6r/slide-10.webp',
                    'https://i.ibb.co/BqjK9zc/slide-11.webp',
                    'https://i.ibb.co/T26rskb/slide-12.webp',
                    'https://i.ibb.co/cwv6rB5/slide-13.webp',
                    'https://i.ibb.co/MN3TLGm/slide-14.webp',
                    'https://i.ibb.co/StTcLv5/slide-15.webp',
                    'https://i.ibb.co/VCFcSDK/slide-16.webp',
                    'https://i.ibb.co/YtK1QXX/slide-17.webp',
                    'https://i.ibb.co/3BV9Cxj/slide-18.webp'
                ]
            },
            {
                'text': 'Учасник спеціалізованого тренінгу з ЗОЖ <span>"Молодіжний працівник"</span> 2020 р. м. Харків',
                'img': [
                    'https://i.ibb.co/m6zbPn4/22.jpg',
                    'https://i.ibb.co/nbTqw54/21.jpg',
                    'https://i.ibb.co/XWgBT4M/20.jpg',
                    'https://i.ibb.co/GPKkPp8/19.jpg',
                    'https://i.ibb.co/gZ9w95t/17.jpg',
                    'https://i.ibb.co/dtFBhyP/13.jpg',
                    'https://i.ibb.co/4sWdVD8/1.jpg',
                    'https://i.ibb.co/ns7qR1s/9.jpg',
                    'https://i.ibb.co/j5HPDqr/10.jpg',
                    'https://i.ibb.co/M7CLsKg/6.jpg',
                    'https://i.ibb.co/jhPb95v/4.jpg',
                    'https://i.ibb.co/PCJ5cXr/2.jpg'
                ]
            },
            {
                'text': 'Учасник та фіналіст тренінгу молодіжних працівників та їх команд <span>"Мережа змін"</span>',
                'img': [
                    'https://i.ibb.co/ySrKBj4/slide-11.jpg',
                    'https://i.ibb.co/zStfmSp/slide-9.jpg',
                    'https://i.ibb.co/q7gjbWh/slide-10.jpg',
                    'https://i.ibb.co/SVd9cJf/slide-17.jpg',
                    'https://i.ibb.co/z7DyJcM/slide-19.jpg',
                    'https://i.ibb.co/3Sfb2pL/slide-32.jpg',
                    'https://i.ibb.co/TMLdDd8/slide-77.jpg',
                    'https://i.ibb.co/gz1bHTp/slide-86.jpg',
                    'https://i.ibb.co/dbr0W9G/slide-99.jpg',
                    'https://i.ibb.co/zf1MXS8/slide-109.jpg',
                    'https://i.ibb.co/gJydR0y/slide-123.jpg',
                    'https://i.ibb.co/n3403CB/slide-127.jpg',
                    'https://i.ibb.co/vH7hWJw/slide-130.jpg',
                    'https://i.ibb.co/QYjxsjg/slide-133.jpg',
                    'https://i.ibb.co/qDkQ2d2/slide-134.jpg',
                    'https://i.ibb.co/59P8j4t/slide-135.jpg',
                    'https://i.ibb.co/wM86rz4/slide-136.jpg',
                    'https://i.ibb.co/fGsCzvX/slide-142.jpg'
                ]
            },
            {
                'text': 'Учасник обласного фестиваля <span>"Дике поле"</span> у 2021 році',
                'img': [
                    'https://i.ibb.co/mBdNwJP/1.jpg',
                    'https://i.ibb.co/PxZ2LN6/2.jpg',
                    'https://i.ibb.co/9y4M5P4/3.jpg',
                    'https://i.ibb.co/7tN6Yxs/4.jpg',
                    'https://i.ibb.co/wRdy0jY/5.jpg',
                    'https://i.ibb.co/2K6P18v/6.jpg',
                    'https://i.ibb.co/3yXV6FY/7.jpg',
                    'https://i.ibb.co/Jkq9GYH/8.jpg',
                    'https://i.ibb.co/Ssc7QtC/9.jpg',
                    'https://i.ibb.co/Yhj2kTk/10.jpg',
                    'https://i.ibb.co/XCBfZjY/11.jpg',
                    'https://i.ibb.co/1fVFrSC/12.jpg',
                    'https://i.ibb.co/k2n4CHh/13.jpg',
                    'https://i.ibb.co/Qddv9hr/14.jpg',
                    'https://i.ibb.co/Gvm0J1M/15.jpg',
                    'https://i.ibb.co/GsxpbCL/16.jpg',
                    'https://i.ibb.co/k06tRnb/17.jpg'
                ]
            },
            {
                'text': 'Учасник обласного семінара <span>"ПроМц"</span> у 2019 - 2021 роках м. Святогірськ',
                'img': [
                    'https://i.ibb.co/sKmXp0m/slide-2.jpg',
                    'https://i.ibb.co/n6SQHnC/slide-1.jpg',
                    'https://i.ibb.co/m6CjVpp/slide-6.jpg',
                    'https://i.ibb.co/gFLyv9v/slide-12.jpg',
                    'https://i.ibb.co/3rSzxMQ/slide-32.jpg',
                    'https://i.ibb.co/bv8XXZ8/slide-33.jpg',
                    'https://i.ibb.co/xXPMfLy/slide-43.jpg',
                    'https://i.ibb.co/8BLTGjw/slide-44.jpg',
                    'https://i.ibb.co/18jgFMX/slide-48.jpg',
                    'https://i.ibb.co/w78rN8y/1.jpg',
                    'https://i.ibb.co/wcpR2W8/2.jpg',
                    'https://i.ibb.co/V9MmPWs/3.jpg',
                    'https://i.ibb.co/gDXFTjZ/4.jpg',
                    'https://i.ibb.co/5jTNsJv/5.jpg',
                    'https://i.ibb.co/p2CtRMp/6.jpg',
                    'https://i.ibb.co/tQgH0Rk/7.jpg',
                    'https://i.ibb.co/tP8KkZH/8.jpg',
                    'https://i.ibb.co/68LVSqj/9.jpg',
                    'https://i.ibb.co/YT0fyjb/10.jpg',
                    'https://i.ibb.co/kSHtL4D/11.jpg',
                    'https://i.ibb.co/vw3kjBP/12.jpg',
                    'https://i.ibb.co/vcYQZjV/13.jpg',
                    'https://i.ibb.co/JpR1BPk/14.jpg',
                    'https://i.ibb.co/YLdmfCB/15.jpg',
                    'https://i.ibb.co/MpqmLHt/16.jpg',
                    'https://i.ibb.co/T12zJ5C/17.jpg',
                    'https://i.ibb.co/vJ11B3K/18.jpg',
                    'https://i.ibb.co/GMpc7qZ/19.jpg',
                    'https://i.ibb.co/541V38D/17.jpg',
                    'https://i.ibb.co/XZmf41c/7.jpg',
                    'https://i.ibb.co/gj5gCbh/2.jpg'
                ]
            },
            {
                'text': 'Учасник обласного семінара <span>"ПроКачМц-2.0"</span> у 2021 році м. Святогірськ',
                'img': [


                ]
            }
        ],
        'desc': '',
        'loc': 'м. Курахове Кураховської ВЦА  Донецької області',
        'data': '2019 рік',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2019 та 2021 роках.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Lider-Hub',
        'name': 'Антон Гладкий',
        'function': 'завідувач',
        'dataName': 'gladkiy',
        'share': true,
        'img': 'https://i.ibb.co/WvTzYkT/gladkiy.jpg',
        'image': 'https://i.ibb.co/xghSF9M/slide-101.jpg',
        'slideImages': [{
                'text': 'Обласний <span>"Фестиваль згуртованості молодіжних центрів"</span>. Один з організаторів та учасників у 2021 році с. Максимільянівка',
                'img': [
                    'https://i.ibb.co/rdvrdVX/slide-54.jpg',
                    'https://i.ibb.co/pZX1r4T/slide-79.jpg',
                    'https://i.ibb.co/mCdrF93/slide-80.jpg',
                    'https://i.ibb.co/bPCRD81/slide-82.jpg',
                    'https://i.ibb.co/Q6hjymp/slide-84.jpg',
                    'https://i.ibb.co/6sTn3q3/slide-87.jpg',
                    'https://i.ibb.co/BVGYmbN/slide-88.jpg',
                    'https://i.ibb.co/HqvzthW/slide-81.jpg'
                ]
            },
            {
                'text': 'Засновник дитячого туристично-спортивного табору <span>"Спадок"</span>',
                'img': [

                ]
            },
            {
                'text': 'Учасник обласного семінара <span>"ПроКачМц-2.0"</span> у 2021 році м. Святогірськ',
                'img': [
                    'https://i.ibb.co/fGRLr4P/16.jpg',
                    'https://i.ibb.co/S3gFgHt/14.jpg',
                    'https://i.ibb.co/BcrFnqc/10.jpg'

                ]
            }
        ],
        'desc': '',
        'loc': 'с. Дачне Кураховської ВЦА  Донецької області',
        'data': '2020 році',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2021 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Вікторія',
        'name': 'Олександра Клименко',
        'function': 'завідувач',
        'dataName': 'klimenko',
        'share': true,
        'img': 'https://i.ibb.co/WBkxr0b/klimenko.jpg',
        'image': 'https://i.ibb.co/wCMjM4M/slide-19.jpg',
        'slideImages': [{
                'text': 'Обласний <span>"Фестиваль згуртованості молодіжних центрів"</span>. Одна з засновників, організаторів та учасників у 2019 році с. Максимільянівка',
                'img': ''
            },
            {
                'text': 'Організатор <span>"Ліги майбутніх поліцейських"</span> м. Мар"їнка',
                'img': ''
            }
        ],
        'desc': '',
        'loc': 'м. Мар"їнка Мар"їнської ВЦА  Донецької області',
        'data': '2016 році',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2019 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Надія',
        'name': 'Данил Глущенко',
        'function': 'завідувач',
        'dataName': 'gluschenko',
        'share': true,
        'img': 'https://i.ibb.co/Hx4bq68/gluschenko.jpg',
        'image': 'https://i.ibb.co/2KWjqq6/slide-1.jpg',
        'slideImages': [{
                'text': 'Один з організаторів та учасників обласного <span>"Фестиваля згуртованості иолодіжних центрів"</span> у 2021 році с. Максимільянівка',
                'img': [
                    'https://i.ibb.co/2KWjqq6/slide-1.jpg',
                    'https://i.ibb.co/YfFsSQ7/slide-8.jpg',
                    'https://i.ibb.co/BnQT4Rc/slide-6.jpg',
                    'https://i.ibb.co/r4mFWpV/slide-39.jpg',
                    'https://i.ibb.co/PcDLSTC/slide-52.jpg',
                    'https://i.ibb.co/3MMYyFh/slide-48.jpg'

                ]
            },
            {
                'text': 'Учасник обласного семінара <span>"ПроКачМц-2.0"</span> у 2021 році м. Святогірськ',
                'img': [
                    'https://i.ibb.co/DLbd8Vh/6.jpg',
                    'https://i.ibb.co/QYsnmL2/5.jpg'

                ]
            },
            {
                'text': 'Учасник та фіналіст тренінгу молодіжних працівників та їх команд <span>"Мережа змін"</span>',
                'img': [
                    'https://i.ibb.co/HBJXbzr/slide-132.jpg',
                    'https://i.ibb.co/cvjTn51/slide-145.jpg',
                    'https://i.ibb.co/TtWXRGq/slide-146.jpg',
                    'https://i.ibb.co/983KnfW/slide-139.jpg',
                    'https://i.ibb.co/Mf0gZB8/slide-72.jpg',
                    'https://i.ibb.co/Vxm6FPZ/slide-59.jpg',
                    'https://i.ibb.co/wd5FdZb/slide-50.jpg',
                    'https://i.ibb.co/wS83yRk/slide-47.jpg',
                    'https://i.ibb.co/HLSFMM1/slide-45.jpg',
                    'https://i.ibb.co/9NBtDnt/slide-43.jpg',
                    'https://i.ibb.co/n3LVFJw/slide-28.jpg',
                    'https://i.ibb.co/sRQ7Bjj/slide-21.jpg',
                    'https://i.ibb.co/FBrBZcM/slide-20.jpg'
                ]
            }

        ],
        'desc': '',
        'loc': 'м. Красногорівка Мар"їнської ВЦА  Донецької області',
        'data': '2017 році',
        'text': 'Один з учасників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> у 2021 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Надія',
        'name': 'Єгор Лагутін',
        'function': 'завідувач',
        'dataName': 'lagutin',
        'share': false,
        'img': 'https://i.ibb.co/Vpbj0Hr/lagutin.jpg',
        'image': 'https://i.ibb.co/2KWjqq6/slide-1.jpg',
        'slideImages': [{
            'text': 'Обласний <span>"Фестиваль згуртованості молодіжних центрів"</span>. Один з засновників, організаторів та учасників у 2019 році с. Максимільянівка',
            'img': ''
        }],
        'desc': '',
        'loc': 'м. Красногорівка Мар"їнської ВЦА  Донецької області',
        'data': '2017 році',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2019 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Крок до мрії',
        'name': 'Катерина Мерзлікіна',
        'function': 'завідувач',
        'dataName': 'merzlikina',
        'share': true,
        'img': 'https://i.ibb.co/WVWX7Tk/merzlikina.jpg',
        'image': 'https://i.ibb.co/BTKXD3V/slide-118.jpg',
        'slideImages': [{
                'text': 'Обласний <span>"Фестиваль згуртованості молодіжних центрів"</span>. Одна з засновників, організаторів та учасників у 2019 та 2021 роках с. Максимільянівка',
                'img': [
                    'https://i.ibb.co/Hq15nz4/slide-27.jpg',
                    'https://i.ibb.co/kJNj45v/slide-26.jpg',
                    'https://i.ibb.co/HDQf9mY/slide-69.jpg',
                    'https://i.ibb.co/1zzCxT6/slide-73.jpg',
                    'https://i.ibb.co/DKYVbQ5/slide-28.jpg',
                    'https://i.ibb.co/KxBNwZh/slide-60.jpg',
                    'https://i.ibb.co/Wxy8XQS/slide-59.jpg'
                ]
            },
            {
                'text': 'Учасник обласного семінару <span>"Молодіжні хаби - ключ до розвитку громад"</span> у 2019 році м. Святогірськ',
                'img': [
                    'https://i.ibb.co/3NMG7SG/slide-31.jpg',
                    'https://i.ibb.co/gdJkkmw/slide-27.jpg',
                    'https://i.ibb.co/JFsByhv/slide-25.jpg',
                    'https://i.ibb.co/hRkKdn3/slide-15.jpg',
                    'https://i.ibb.co/s25BF3D/slide-18.jpg',
                    'https://i.ibb.co/0hMypJL/slide-13.jpg',
                    'https://i.ibb.co/WHGn9Dx/slide-14.jpg',
                    'https://i.ibb.co/6PgW8Yx/slide-9.jpg',
                    'https://i.ibb.co/9bzbbry/slide-8.jpg',
                    'https://i.ibb.co/26Cm6h8/slide-5.jpg',
                    'https://i.ibb.co/YTx6HyD/slide-10.jpg',
                    'https://i.ibb.co/FnNP6Lz/slide-4.jpg',
                    'https://i.ibb.co/HgKCN76/slide-2.jpg',
                    'https://i.ibb.co/720fDnQ/slide-34.jpg',
                    'https://i.ibb.co/YhTywV4/slide-47.jpg',
                    'https://i.ibb.co/mDCysYf/slide-53.jpg',
                    'https://i.ibb.co/NtPB0bC/slide-54.jpg',
                    'https://i.ibb.co/wsXXwqj/slide-56.jpg',
                    'https://i.ibb.co/xqMFwkQ/slide-61.jpg',
                    'https://i.ibb.co/SN71fCQ/slide-63.jpg'
                ]
            },
        ],
        'desc': '',
        'loc': 'с. Новомихайлівка Мар"їнської ВЦА  Донецької області',
        'data': '28 грудня 2018 року',
        'text': 'Один з засновників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> та організаторів його у 2019 та 2021 роках.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'ElizavetCity',
        'name': 'Ольга Грищенко',
        'function': 'завідувач',
        'dataName': 'grischenko',
        'share': true,
        'img': 'https://i.ibb.co/gTp13MM/grischenko.jpg',
        'image': 'https://i.ibb.co/LSPm3bx/slide-121.jpg',
        'slideImages': [{
                'text': 'Фестиваль згуртованості молодіжних центрів"</span>. Одна з організаторів та учасникыв у 2021 році.',
                'img': [
                    'https://i.ibb.co/7SFj4js/slide-74.jpg',
                    'https://i.ibb.co/2PnbkRW/slide-89.jpg'
                ]
            },
            {
                'text': 'Учасник <span>прямого ефіру</span> в молодіжному центрі <span>"Мексика"</span> 2021 року',
                'img': [
                    'https://i.ibb.co/Jqkbn3d/slide-5.jpg',
                    'https://i.ibb.co/mGLKzXs/slide-6.jpg',
                    'https://i.ibb.co/sHGzqMb/slide-7.jpg'
                ]
            },
            {
                'text': 'Учасник та фіналіст тренінгу молодіжних працівників та їх команд <span>"Мережа змін"</span>',
                'img': [
                    'https://i.ibb.co/GkmpnYQ/slide-15.jpg',
                    'https://i.ibb.co/0hByTfJ/slide-22.jpg',
                    'https://i.ibb.co/cr6khXJ/slide-25.jpg',
                    'https://i.ibb.co/Rpjx0yY/slide-26.jpg',
                    'https://i.ibb.co/pwg461D/slide-31.jpg',
                    'https://i.ibb.co/gFNzHVM/slide-51.jpg',
                    'https://i.ibb.co/kyZ8hWG/slide-54.jpg',
                    'https://i.ibb.co/1ZDsV64/slide-67.jpg',
                    'https://i.ibb.co/BzWWg3t/slide-71.jpg',
                    'https://i.ibb.co/JsfzCc5/slide-88.jpg',
                    'https://i.ibb.co/sQKJNzk/slide-106.jpg',
                    'https://i.ibb.co/zf1MXS8/slide-109.jpg',
                    'https://i.ibb.co/mFDTDCn/slide-143.jpg',
                    'https://i.ibb.co/FgSd0gk/slide-148.jpg',
                    'https://i.ibb.co/WB4zkFB/slide-149.jpg'
                ]
            }

        ],
        'desc': '',
        'loc': 'с. Єлізаветівка Мар"їнської ВЦА  Донецької області',
        'data': '2019 році',
        'text': '<span>"Фестиваль згуртованості молодіжних центрів"</span>. Одна з організаторів та учасникыв у 2021 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'ElizavetCity',
        'name': 'Дмитро Гришков',
        'function': 'завідувач',
        'dataName': 'grishkov',
        'share': false,
        'img': 'https://i.ibb.co/K0smCWP/grishko.jpg',
        'image': 'https://i.ibb.co/LSPm3bx/slide-121.jpg',
        'slideImages': [{
            'text': 'Учасник обласного семінара <span>"ПроКачМц-2.0"</span> у 2021 році м. Святогірськ',
            'img': [
                'https://i.ibb.co/YWkQfLx/1.jpg',
                'https://i.ibb.co/NZf7FcX/8.jpg',
                'https://i.ibb.co/QfJ3NZw/13.jpg',
                'https://i.ibb.co/VNWgvk2/18.jpg',
                'https://i.ibb.co/DLbd8Vh/6.jpg',
                'https://i.ibb.co/7G6c3Mg/4.jpg',
                'https://i.ibb.co/hKTkZgg/15.jpg'

            ]
        }],
        'desc': '',
        'loc': 'с. Єлізаветівка Мар"їнської ВЦА  Донецької області',
        'data': '2019 році',
        'text': ''
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Гармонія',
        'name': 'Юлія Кольчик',
        'function': 'завідувач',
        'dataName': 'kolchik',
        'share': true,
        'img': 'https://i.ibb.co/DwcSNXQ/kolchik.jpg',
        'image': 'https://i.ibb.co/cN4zk0G/slide-20.jpg',
        'slideImages': [{
                'text': '<span>"Фестиваль згуртованості молодіжних центрів"</span> у 2021 році.',
                'img': [
                    'https://i.ibb.co/cN4zk0G/slide-20.jpg',
                    'https://i.ibb.co/QKsqKTZ/slide-19.jpg',
                    'https://i.ibb.co/yWJQx5g/slide-15.jpg',
                    'https://i.ibb.co/LZ4HWKY/slide-29.jpg'
                ]
            },
            {
                'text': 'Учасник  тренінгу молодіжних працівників та їх команд <span>"Мережа змін"</span>',
                'img': [
                    'https://i.ibb.co/3dm4q5C/slide-55.jpg',
                    'https://i.ibb.co/CmCCKs6/slide-70.jpg',
                    'https://i.ibb.co/QkZc2f6/slide-69.jpg',
                    'https://i.ibb.co/q1g2hBz/slide-68.jpg',
                    'https://i.ibb.co/Xz7kHX2/slide-56.jpg',
                    'https://i.ibb.co/KjsDkbb/slide-42.jpg',
                    'https://i.ibb.co/QMrRfxq/slide-38.jpg',
                    'https://i.ibb.co/VNy5dT0/slide-36.jpg',
                    'https://i.ibb.co/Rpjx0yY/slide-26.jpg',
                    'https://i.ibb.co/WB4zkFB/slide-149.jpg',
                    'https://i.ibb.co/yh9s0mN/slide-113.jpg',
                    'https://i.ibb.co/mtkBFTf/slide-112.jpg'

                ]
            }
        ],
        'desc': '',
        'loc': 'с. Костянтинівка Мар"їнської ВЦА  Донецької області',
        'data': '2019 році',
        'text': 'Один з організаторів та учасників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> у 2021 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Fox',
        'name': 'Марина Ткаченко',
        'function': 'завідувач',
        'dataName': 'tkachenko',
        'share': true,
        'img': 'https://i.ibb.co/mvNgFtb/marina.jpg',
        'image': 'https://i.ibb.co/n0sdYQ6/slide-4.jpg',
        'slideImages': [{
            'text': 'Учасник щорічних військово-патріотичних ігор та спортивних змаганнь <span>"Завжди разом"</span> за підтримки цивільно-військового співробітництва с. Максимільянівка у 2019 року',
            'img': [
                'https://i.ibb.co/1ZDdYFC/slide-3.jpg',
                'https://i.ibb.co/s6dymcD/slide-4.jpg',
                'https://i.ibb.co/bmv1s9h/slide-5.jpg',
                'https://i.ibb.co/yQYpSr1/slide-7.jpg',
                'https://i.ibb.co/qBxkW7c/slide-8.jpg',
                'https://i.ibb.co/p1YCQgj/slide-9.jpg',
                'https://i.ibb.co/Z6hvTcD/slide-10.jpg',
                'https://i.ibb.co/fvGq4YG/slide-11.jpg',
                'https://i.ibb.co/q0JdR2k/slide-12.jpg',
                'https://i.ibb.co/YDcgvNw/slide-13.jpg',
                'https://i.ibb.co/3Bb1P2Q/slide-14.jpg',
                'https://i.ibb.co/K9f089r/slide-15.jpg',
                'https://i.ibb.co/3s1CS0F/slide-19.jpg',
                'https://i.ibb.co/23S8YHr/slide-20.jpg',
                'https://i.ibb.co/LtZkSRR/slide-21.jpg',
                'https://i.ibb.co/Y8wYKkN/slide-26.jpg',
                'https://i.ibb.co/1m0fjpv/slide-27.jpg',
                'https://i.ibb.co/H7KpGwx/slide-28.jpg',
                'https://i.ibb.co/q5Yb7Fg/slide-29.jpg',
                'https://i.ibb.co/2FtKVLP/slide-30.jpg',
                'https://i.ibb.co/LNk5X5M/slide-31.jpg',
                'https://i.ibb.co/vjsJv2X/slide-32.jpg',
                'https://i.ibb.co/LtZKG4L/slide-33.jpg',
                'https://i.ibb.co/DMgLgyW/slide-34.jpg',
                'https://i.ibb.co/7jYPKyc/slide-35.jpg',
                'https://i.ibb.co/ZccVXPS/slide-36.jpg',
                'https://i.ibb.co/yX48VJm/slide-37.jpg',
                'https://i.ibb.co/f877dNJ/slide-38.jpg',
                'https://i.ibb.co/dDgy2mZ/slide-39.jpg',
                'https://i.ibb.co/RP1fvhJ/slide-40.jpg',
                'https://i.ibb.co/jMyBRP5/slide-41.jpg',
                'https://i.ibb.co/17KJJp9/slide-42.jpg',
                'https://i.ibb.co/zNFPMD9/slide-44.jpg',
                'https://i.ibb.co/k3dJnp2/slide-45.jpg',
                'https://i.ibb.co/kQ6Lk1d/slide-48.jpg'
            ]
        }],
        'desc': '',
        'loc': 'с. Катеринівка Мар"їнської ВЦА  Донецької області',
        'data': '2019 році',
        'text': 'Один з активних учасників обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> у 2019 році.'
    },
    {
        'title': 'Молодіжний центр',
        'yourName': 'Fox',
        'name': 'Тетяна Василенко',
        'function': 'завідувач',
        'dataName': 'vasilenko',
        'share': false,
        'img': 'https://i.ibb.co/z2ZvmsY/vasilenko.jpg',
        'image': 'https://i.ibb.co/n0sdYQ6/slide-4.jpg',
        'slideImages': [{
            'text': 'Учасник обласного семінара <span>"ПроКачМц-2.0"</span> у 2021 році м. Святогірськ',
            'img': [
                'https://i.ibb.co/mFbx62t/3.jpg',
                'https://i.ibb.co/GxsD41D/11.jpg',
                'https://i.ibb.co/NjKrSKx/12.jpg',
                'https://i.ibb.co/wSfNhVF/9.jpg',
                'https://i.ibb.co/YWkQfLx/1.jpg',
                'https://i.ibb.co/BcrFnqc/10.jpg'

            ]
        }],
        'desc': '',
        'loc': 'с. Катеринівка Мар"їнської ВЦА  Донецької області',
        'data': '2019 році',
        'text': ''
    },
    {
        'title': 'КПНЗ',
        'yourName': 'ДОДМЦ',
        'name': 'Аліна Сорокіна',
        'function': 'директор',
        'dataName': 'sorokina',
        'share': true,
        'img': 'https://i.ibb.co/Fbx4fGk/sorokima.jpg',
        'image': 'https://i.ibb.co/SrCQGNC/slide-1.jpg',
        'slideImages': [{
            'text': '',
            'img': [
                'https://i.ibb.co/sgSgSKg/slide-1.webp',
                'https://i.ibb.co/fMMhcZT/slide-2.webp',
                'https://i.ibb.co/xf1V4fs/slide-3.webp',
                'https://i.ibb.co/nzLjK1L/slide-4.webp',
                'https://i.ibb.co/LPMTRbG/slide-5.webp',
                'https://i.ibb.co/MZZ5chq/slide-6.webp',
                'https://i.ibb.co/pwgWxKg/slide-7.webp',
                'https://i.ibb.co/Y0jytN0/slide-8.webp',
                'https://i.ibb.co/xFGTxZr/slide-9.webp',
                'https://i.ibb.co/BByxFz8/slide-10.webp',
                'https://i.ibb.co/SnVd28J/slide-11.webp',
                'https://i.ibb.co/xCg5Qxs/slide-12.webp',
                'https://i.ibb.co/qrWmzpz/slide-13.webp',
                'https://i.ibb.co/qNdJ0V5/slide-14.webp',
                'https://i.ibb.co/gwPBLR4/slide-15.webp'
            ]
        }],
        'desc': '',
        'loc': 'м. Краматорськ Донецької області',
        'data': '2009 році',
        'text': 'Спонсор обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> у 2021 році.'
    },
    {
        'title': 'ГО',
        'yourName': 'Теплиця',
        'name': 'Ганна Авдіянц',
        'function': 'директор',
        'dataName': 'avdiyants',
        'share': true,
        'img': 'https://i.ibb.co/L9GLK4X/avdiyants.jpg',
        'image': 'https://i.ibb.co/JzGywYW/slide-92.jpg',
        'slideImages': [{
                'text': 'Організатор тренінгу молодіжних працівників та їх команд <span>"Мережа змін"</span>',
                'img': [
                    'https://i.ibb.co/pjPsbfX/slide-75.jpg',
                    'https://i.ibb.co/L15x85Q/slide-103.jpg',
                    'https://i.ibb.co/0qmq52V/slide-107.jpg',
                    'https://i.ibb.co/xMnqgH4/slide-155.jpg',
                    'https://i.ibb.co/HFdwJ5T/slide-179.jpg',
                    'https://i.ibb.co/9HRVFx9/slide-178.jpg',
                    'https://i.ibb.co/D7yfq0P/slide-175.jpg',
                    'https://i.ibb.co/7p7ztdR/slide-174.jpg',
                    'https://i.ibb.co/x7JQPyM/slide-172.jpg',
                    'https://i.ibb.co/DMmJ6JT/slide-116.jpg',
                    'https://i.ibb.co/M7rqXrW/slide-93.jpg',
                    'https://i.ibb.co/WBVCkrG/slide-98.jpg',
                    'https://i.ibb.co/sbyY8Wr/slide-89.jpg',
                    'https://i.ibb.co/6mn3m6r/slide-66.jpg',
                    'https://i.ibb.co/QQG63YR/slide-58.jpg',
                    'https://i.ibb.co/5x36j2h/slide-48.jpg',
                    'https://i.ibb.co/vH2Dyps/slide-29.jpg',
                    'https://i.ibb.co/KVR7vpX/slide-27.jpg',
                    'https://i.ibb.co/7zf1fxX/slide-13.jpg',
                    'https://i.ibb.co/6NMQNzN/slide-1.jpg'
                ]
            },
            {
                'text': 'Одна з ініціаторів та організаторів свята до <span>"Дня вишиванки"</span> м. Слав"янськ у 2021 році</.span>',
                'img': [
                    'https://i.ibb.co/G0H9tnV/slide-1.jpg',
                    'https://i.ibb.co/6R51M9n/slide-2.jpg',
                    'https://i.ibb.co/KGwDNq9/slide-3.jpg',
                    'https://i.ibb.co/nPT6xkQ/slide-4.jpg',
                    'https://i.ibb.co/x8d9y9Y/slide-5.jpg',
                    'https://i.ibb.co/VSmyncD/slide-6.jpg',
                    'https://i.ibb.co/VWSfX0G/slide-7.jpg',
                    'https://i.ibb.co/0Jvkqv2/slide-8.jpg',
                    'https://i.ibb.co/cc8Spxn/slide-9.jpg',
                    'https://i.ibb.co/wMcbqt7/slide-10.jpg',
                    'https://i.ibb.co/Fh04dKs/slide-11.jpg',
                    'https://i.ibb.co/vwnHx8g/slide-12.jpg',
                    'https://i.ibb.co/yyHXDwL/slide-13.jpg',
                    'https://i.ibb.co/nc0YzcF/slide-14.jpg',
                    'https://i.ibb.co/Pw6qCfJ/slide-15.jpg',
                    'https://i.ibb.co/0J453s7/slide-16.jpg',
                    'https://i.ibb.co/DrSy428/slide-17.jpg',
                    'https://i.ibb.co/xfD4zPC/slide-18.jpg',
                    'https://i.ibb.co/m6YmZ0Y/slide-19.jpg'
                ]
            },
            {
                'text': 'Спікер обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> у 2021 році',
                'img': [
                    'https://i.ibb.co/JzGywYW/slide-92.jpg',
                    'https://i.ibb.co/2PnbkRW/slide-89.jpg',
                    'https://i.ibb.co/Vqxv9MX/slide-99.jpg'
                ]
            }
        ],
        'desc': '',
        'loc': 'м. Слав"янськ Донецької області',
        'data': '2009 році',
        'text': 'Спікер обласного <span>"Фестиваля згуртованості молодіжних центрів"</span> у 2021 році.'
    }

]